### ISSUE TITLE
天翼云盘签到仓库被禁用了

### ISSUE THREAD

**Issue by 610364023** [xtyuns/TTEA4j#1]
![2023-03-28_12-57-15](https://user-images.githubusercontent.com/45279039/228132634-1aa3b3b5-c66d-479a-9859-2d99262981a6.jpg)

**Comment by xtyuns** [comment]
当初创建 `cloud189app-action` 项目的目的是进行相关内容的学习和研究，现在这个项目已经完成了它的使命，因此将不再维护该项目
